<?php

namespace AppBundle\Repository;

/**
 * InvoiceRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRequestRepository extends \Doctrine\ORM\EntityRepository {

    public function findByEmail($email, $start = 0, $limit = 10) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i
                FROM AppBundle:InvoiceRequest i INNER JOIN AppBundle:User u WITH (i.user_id = u.id)
                WHERE u.email = :email'
            )->setParameter('email', $email)
            ->setFirstResult($start)
            ->setMaxResults($limit)
            ->getResult();
    }
}
