<?php

namespace AppBundle\Repository;

/**
 * InvoiceRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
